apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wvdy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wvdy
    app.kubernetes.io/part-of: byoc-app-owpa
  name: wvdyqv1s
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: wvdy
    weight: null
status: {}
